###
# Modbus Settings
###
modbus:
  id: modbus_zp
  uart_id: uart_modbus_zp
  #send_wait_time: 2000ms

modbus_controller:
  - id: zp
    address:          0x1
    modbus_id:        modbus_zp
    setup_priority:   -10
    update_interval:  15s
    command_throttle: 200ms
    offline_skip_updates: 100
