sensor:
  # This is handy to get your hand on the right manual :)
  - platform: modbus_controller
    name: "${device_name} Modbus version"
    id: gw_ModbusVersion
    icon: mdi:information
    register_type: holding
    address: 88
    entity_category: diagnostic
    # Divide the number by 100 to represent the true V number
    filters:
    - multiply: 0.01
  # See how long your inverter has been producing in secconds
  - platform: modbus_controller
    name: "${device_name} Total Working Time"
    id: gw_ModbusVersion
    icon: mdi:clock-outline
    unit_of_measurement: "seconds"
    address: 57
    entity_category: diagnostic
    # Divide the number by 100 to represent the true V number
    filters:
    - multiply: 0.01

text_sensor:
  # This is only a part of the serial? this results in a 2 letter code: AK
  - platform: modbus_controller
    name: "${device_name} Firmware Version"
    id: gw_FirmwareVersion
    address: 9
    register_count: 3
    register_type: holding
    internal: true
    entity_category: diagnostic