esphome:
  name: zp-rs485
  friendly_name: ZP-RS485
  comment: Growatt MIN 3600 LT X

substitutions:
  device_name: Growatt

# Enable logging
logger:
# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  - platform: esphome
    password: !secret ota_password
wifi:
  # Local of things (no internet)
  ssid: !secret lot_wifi_ssid
  password: !secret lot_wifi_password
  fast_connect: true
  power_save_mode: light
  use_address: !secret ip_address
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Zp-Rs485 Fallback Hotspot"
    password: "GrowattFallback"
##
# Enable captive portal  
captive_portal:
##
# Debugging webserver
web_server:
  port: 80
  version: 3

packages:
  remote_package:
    url: https://github.com/william-sy/esphome-growatt
    ref: main
    refresh: 0s
    files: [
      esphome/base/base.yaml,
      esphome/base/board-esp32-atom-light.yaml,
      #esphome/i18n/EN.yaml,
      #esphome/i18n/NL.yaml,
      esphome/inverter/inverter.yaml,
      # Read the file first!!!!!!!
      # This can do permanent dmage to the inverter
      #esphome/inverter/danger.yaml,
      #esphome/inverter/info.yaml,
      esphome/inverter/pv1.yaml,
      esphome/inverter/pv2.yaml
    ]